Milestone 2
SajjadAhmad14/Bookstore-React-Redux pull request #2
Opened 2021-07-11 14:32 UTC by SajjadAhmad14

- Added components directory under src.
- Added containers directory under src.
- Added actions directory under src.
- Added reducers directory under src.
- Added reducers and actions.
- Created store.

2021-07-12 04:12 UTC, rindrajosia requested changes
Changes Required :red_circle:
To Highlight: :angel:

- The src/index.js imports `{ Provider }` from `react-redux` :+1: 
- App and Book components are placed in `src/components` directory :100: 

To improve :factory_worker: [REQUIRED]:

- [x] Comments: It’s better to delete commented piece of codes. If you need to review a previous version of your code, use git history (screenshot from Pathwright)
- **src/index.js:** 
- [x] it adds example books to the initial state object (please check my comment below :arrow_double_down: )
- [x] it wraps `App` in `Provider` and assign the whole thing into a variable:
```javascript
const wrappedApp = (
  <Provider store={store}>
    <App />
  </Provider>
);
```


- [x]  **`App` component:**  should only display `BooksList` and `BookForm` components
- 
- [x] **`Book` component:** should represent single row of books with id, title and category [screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone2/Book/RepresentARowInBooksTable.png)
- 
- **`BooksList` component:**
- [x] it is placed in `src/containers` directory
- [x] it connects to Redux store, using the `connect()` function or [Redux hooks](https://react-redux.js.org/api/hooks), and fetches books from the state [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone2/BooksList/ConnetToReduxHooks.png) from [pathwright](https://microverse.pathwright.com/library/react-redux-v10/188148/path/step/107676536/)
- [x] it uses `mapStateToProps` to fetch books from the `store`
- [ ] it displays books list in html table using `Book` component [screenshot from pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone2/BooksList/BooksAsTable.png)
- [ ] it passes a `book` object as a prop to each `Book` component
- 
- [x] **`BookForm` component** : it is placed in `src/containers` directory
- 
- [x] **`index.js` reducer** : it combines app specific reducers (
[screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone2/ReducxReducers/CombinesAppReducers.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896827/))
```javascript
import { combineReducers } from 'redux'
import books from './books'

export default combineReducers({
  books
})

```

- 
- [ ] **`books.js` reducer** : it implements `CREATE_BOOK` and `REMOVE_BOOK` actions [screenshot from pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone2/ReducxReducers/CreateAndRemoveReducers.png)
- 
- [ ] I got an error when I open your APP on my browser.
![1](https://user-images.githubusercontent.com/58552748/125229036-937d1f80-e2de-11eb-88ee-dd15bb0e0ebb.gif)

Nice to have [OPTIONAL] :

- [ ] 

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

2021-07-12 04:12 UTC, rindrajosia commented on src/components/App.js
> +  </div>
It only displays `BooksList` and `BookForm` components

2021-07-12 04:12 UTC, rindrajosia commented on src/components/Book.js
> +  </div>
it represents single row of books with id, title and category [screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone2/Book/RepresentARowInBooksTable.png)

2021-07-12 04:12 UTC, rindrajosia commented on src/components/BookList.js
> +// export default connect(mapStateToProps, null)(BookList);
Comments: It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2021-07-12 04:12 UTC, rindrajosia commented on src/components/BookList.js
> +// import { connect } from 'react-redux';
Comments: It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2021-07-12 04:12 UTC, rindrajosia commented on src/components/BookList.js
> +);
* it connects to Redux store, using the `connect()` function or [Redux hooks](https://react-redux.js.org/api/hooks), and fetches books from the state [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone2/BooksList/ConnetToReduxHooks.png) from [pathwright](https://microverse.pathwright.com/library/react-redux-v10/188148/path/step/107676536/)
* it uses `mapStateToProps` to fetch books from the `store`
* it displays books list in html table using `Book` component [screenshot from pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone2/BooksList/BooksAsTable.png)
* it passes a `book` object as a prop to each `Book` component

2021-07-12 04:12 UTC, rindrajosia commented on src/components/BookTable.js
> +}
I think, you don't need this file

2021-07-12 04:12 UTC, rindrajosia commented on src/index.js
> +const store = createStore(state, booksReducer);
It should be: const store = createStore(booksReducer,state)

2021-07-12 04:12 UTC, rindrajosia commented on src/reducers/books.js
> +export default booksReducer;
It is just an example, feel free to change it based on your src/actions/index.js:
```javascript
const books = (state, action) => {
  switch (action.type) {
    case CREATE_BOOK: {
      return {
        books: [...state.books, action.payload],
      };
    }
    case REMOVE_BOOK: {
      const { id } = action.payload;
      return {
        books: state.books.filter(book => book.id !== id),
      };
    }
    default:
      return state;
  }
};

```

2021-07-14 15:39 UTC, SajjadAhmad14 commented on src/components/App.js
> +  </div>
Done!

2021-07-15 08:21 UTC, SajjadAhmad14 commented on src/components/Book.js
> +  </div>
Done!

2021-07-15 08:21 UTC, SajjadAhmad14 commented on src/components/BookList.js
> +);
Done!

2021-07-15 08:21 UTC, SajjadAhmad14 commented on src/components/BookTable.js
> +}
Thanks for pointing it out!

2021-07-15 13:49 UTC, Elbie-em approved these changes
### STATUS: APPROVED ✅ 

Hi @SajjadAhmad14, awesome job implementing the changes requested by the previous TSE.

*All the best and keep up the good work* 💪 

> Elbie Moonga (Part-time TSE)

> Github (@Elbie-em)
> Slack (Elbie Moonga)
> Twitter ([@ElbieEm](https://twitter.com/ElbieEm))
> LinkedIn([Elbie Moonga](https://www.linkedin.com/in/elbiemoonga/))

2021-07-15 14:31 UTC, merged