Milestone 3
SajjadAhmad14/Bookstore-React-Redux pull request #3
Opened 2021-07-18 18:26 UTC by SajjadAhmad14

- Show books on the table.
- Use useDispatch hooks.
- Use useSelector hooks.
- Add books to Redux store.
- Remove books from Redux store.

2021-07-18 23:28 UTC, voscarmv requested changes
# Impressive work.  💻 👀 ✨

## However, there are some changes required 👀 🧰 🔨 🔧
- Please read my code comments on the implementation of the book removal methods and apply all necessary fixed.
- You may optionally use `map` for your category selector, instead of hardcoding the options one by one.

### Submit these changes and request a new code review! 😄 👍

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier)🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

2021-07-18 23:28 UTC, voscarmv commented on src/containers/BooksForm.js
> +          onChange={(e) => { setBook({ ...book, title: e.target.value }); }}
- [ ] Please implement a `handleChange` method and use that for `onChange` here, instead of hardcoding it into the component.

2021-07-18 23:28 UTC, voscarmv commented on src/containers/BooksList.js
> +const BooksList = () => {
- [ ] Please implement a `handleBookRemove` method here.

2021-07-18 23:28 UTC, voscarmv commented on src/containers/BooksList.js
> +        ))}
- [ ] Once you implement `handleBookRemove`, pass it to the `Book` component in order to use it in the `Remove book` button.
- [ ] In the `Book` component, use the `handleBookRemove` method for the `onClick` event of the `RemoveBook` button.

2021-07-18 23:28 UTC, voscarmv commented on src/containers/BooksForm.js
> +          <option value={CATEGORIES[6]}>{CATEGORIES[6]}</option>
- [ ] **[OPTIONAL]** You may use `map` here instead of listing the categories one by one.

2021-07-29 02:50 UTC, voscarmv requested changes
# Impressive work.  💻 👀 ✨

## However, there are some changes required 👀 🧰 🔨 🔧
- I noticed some of the changes from the previous review were not implemented. Please apply the following fixes: 
- https://github.com/SajjadAhmad14/Bookstore-React-Redux/pull/3#discussion_r671913303
- https://github.com/SajjadAhmad14/Bookstore-React-Redux/pull/3#discussion_r671913494

### Submit these changes and request a new code review! 😄 👍

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier)🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

2021-07-29 09:55 UTC, afanimartin approved these changes
## Approved 👍🏿 👍🏿 👍🏿 
Nice work making the requested changes.
- correct implementation of the `handleBookRemove` function as requested

### Martin Afani
#### Slack: whiz25

2021-07-29 10:07 UTC, merged