Milestone 4
SajjadAhmad14/Bookstore-React-Redux pull request #4
Opened 2021-08-01 18:22 UTC by SajjadAhmad14

- Add filter category to Redux store.
- Use useState, useDispatch, and useSelecter hooks.

2021-08-01 23:14 UTC, oloomoses requested changes
Hi @SajjadAhmad14  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request
- [ ] Kindly check again and confirm that you have submitted the correct milestone. Not a single requirement has been implemented for this milestone. If you are sure that you have submitted the correct milestone, then I would suggest that you carefully read through the project requirements again. Below is a screenshot of the milestone requirements.
![Screenshot from 2021-08-02 01-58-17](https://user-images.githubusercontent.com/20245164/127788136-cd97e901-54d0-4c16-8188-6a24065fa38b.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

2021-08-02 14:02 UTC, bellom requested changes
## Hi @SajjadAhmad14  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Changes Required! ♻️ 

**Kindly check my comments under this review;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best**

2021-08-02 14:02 UTC, bellom commented on src/containers/Categories.js
> +};
Opps 🤦 , let's stick to best practice.

In milestone 2, you were introduced to the `component` and `container` folders.

Kindly improve the project structure such that you have components for stateless components and a container/page folder for other components that use the state.

React bindings for Redux separate presentational components from container components. This approach can make your app easier to understand and allow you to more easily reuse components. In your components directory (presentational components) you have components that are not connected to the Redux store, and on your containers directory, you have components that are connected to the Redux store. Read More... https://www.pluralsight.com/guides/how-to-structure-redux-components-and-containers

In your case, it should be `src/component/Categories`

2021-08-02 14:35 UTC, SajjadAhmad14 commented on src/containers/Categories.js
> +};
Hi,
Thank you so much for making the presentational and stateful components clear!

2021-08-02 14:46 UTC, mahmoud717 approved these changes
### STATUS: APPROVED ✔️ ✔️ 

**hi @SajjadAhmad14**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

2021-08-16 13:33 UTC, merged