Milestone 5-Add style to app.
SajjadAhmad14/Bookstore-React-Redux pull request #5
Opened 2021-08-11 18:07 UTC by SajjadAhmad14

- Added a navigation bar.
- Created a card for the book.
- Added style to book form.

2021-08-11 18:57 UTC, afanimartin requested changes
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Nice work on the design for the app. You did well.

### Changes 🔕 🔕 🔕 
- align the user avatar with the list of books vertically
- remove the category selector above the list of books. The given mock-up doesn't have that.
- add a sample list of books
- make sure you clone the given mock-up exactly

#### Reference the given mock-up below
![main-ui](https://user-images.githubusercontent.com/80149314/129086810-3b2d4967-babd-4a5f-adc2-6fdce81de97c.png)


### Martin Afani
#### Slack: whiz25

2021-08-13 08:42 UTC, SajjadAhmad14 commented
> ## Changes Required 🙏🏿 🙏🏿 🙏🏿
> Nice work on the design for the app. You did well.
> 
> ### Changes   
> * align the user avatar with the list of books vertically
> * remove the category selector above the list of books. The given mock-up doesn't have that.
> * add a sample list of books
> * make sure you clone the given mock-up exactly
> 
> #### Reference the given mock-up below
> ![main-ui](https://user-images.githubusercontent.com/80149314/129086810-3b2d4967-babd-4a5f-adc2-6fdce81de97c.png)
> 
> ### Martin Afani
> #### Slack: whiz25

2021-08-13 08:49 UTC, SajjadAhmad14 commented
Thank you for your kind review! Can you please specify which feature is missing from the design? I have worked on all the compulsory requirements and all other requirements you mentioned can be optional! Thanks!

2021-08-13 09:04 UTC, afanimartin requested changes
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Nice attempt on the requested changes. You did well.
However, you didn't pay close attention to the given mock-up. This is a clone and therefore what you produce must look exactly like the given design.
There are still a lot of changes to make

#### This is the given design
![main-ui](https://user-images.githubusercontent.com/80149314/129332914-3282f953-a8c8-44e0-871e-060f28340fd1.png)

#### This is your design
![Screenshot from 2021-08-13 10-59-43](https://user-images.githubusercontent.com/80149314/129332972-bae4e022-bc73-4d64-b580-cc5f1e76d9d6.png)

Do you spot any differences? I do that's why am asking for more changes. Make sure you reproduce the given design.

### Martin Afani
#### Slack: whiz25

2021-08-13 13:20 UTC, oloomoses requested changes
Hi @SajjadAhmad14, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] The filter should be in the page header beside the CATEGORIES placeholder.
- [ ] According to the given design, the border for the form inputs is faded. Kindly work on the styling to match that of the given design
![Screenshot from 2021-08-13 16-10-51](https://user-images.githubusercontent.com/20245164/129362193-dc2b13df-7245-463e-b395-ff98a3837a0c.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Kindly consider:
- [ ] fixing the errors displayed in the browser console
![Screenshot from 2021-08-13 16-18-23](https://user-images.githubusercontent.com/20245164/129363008-3f81aac8-a0e3-4109-9385-a5c5bdf11c67.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_Slack: Oloo Moses_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-16 12:08 UTC, addod19 approved these changes
### Hi @SajjadAhmad14 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

__Happy coding__ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-08-16 12:08 UTC, addod19 commented on src/App.css
> +.update {
### Optional
- It would be better if we remove the border on the progress update button, the UI will look more user friendly if we add `border: none` to the styling

2021-08-16 13:33 UTC, merged